config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root  'pins#index'
  get   '/about' => 'home#about'


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates :pun_text, presence: { message: "Pun text must contain the text of the pun itself!" }
  validates :category, presence: { message: "Be sure to choose the category your pun falls under! Example: Animals" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 15)
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: "Pin was successfully created"
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Pin was successfully updated"
    else
      render action: 'edit'
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:pun_text, :image, :category)
    end
end

def correct_user
  @pin = current_user.pins.find_by(id: params[:id])
  redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_jumbotron.html.erb
<div class="jumbotron center">
  <h1>Welcome to Punterest</h1>

  <p>A website dedicated to saving the best puns!</p>
  <% if user_signed_in? %>
    <%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-warning' %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
    <%= link_to 'List Pins', pins_path, class: 'btn btn-success' %>
  <% else %>
    <%= link_to 'Login', new_user_session_path, class: 'btn btn-danger' %>
    <%= link_to 'Join', new_user_registration_path, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/home/about.html.erb
<h1>About Puntrest</h1>

app/views/home/index.html.erb
<div class="jumbotron center">
  <h1>Welcome to Punterest</h1>

  <p>A website dedicated to saving the best puns!</p>
  <% if user_signed_in? %>
    <%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-warning' %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
    <%= link_to 'List Pins', pins_path, class: 'btn btn-success' %>
  <% else %>
    <%= link_to 'Login', new_user_session_path, class: 'btn btn-danger' %>
    <%= link_to 'Join', new_user_registration_path, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
    <div class="text-center">
        <ul class="list-inline">
           <li><%= mail_to "downing034@gmail.com", "REPORT AN ISSUE" %></li>  |
           <li>Copyright <i class="fa fa-copyright"></i> <span style="color:#CC7C21">Paul Downing</span> All Rights Reserved</li>
        </ul>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Punterest', root_path, class: 'navbar-brand', id: 'brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right" id="nav-links">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'Add Pun', new_pin_path %></li>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Join', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
 </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Punterest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>
  <div class="container">
    <% flash.each do |name, msg| %>
	    <% if msg.is_a?(String) %>
	      <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
	        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <%= content_tag :div, msg, :id => "flash_#{name}" %>
	      </div>
	      <% end %>
	    <% end %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>

</body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :pun_text, "Pun" %>
    <%= f.text_field :pun_text, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :category %>
    <%= f.text_field :category, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>
  <div class="actions form-group">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="panel panel-default">
  <div class="panel panel-heading">
    <h1>Editing Pun</h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
  <div class="panel-footer">
    <%= link_to 'Show', @pin %> |
    <%= link_to 'Back', pins_path %>
  </div>
</div>

app/views/pins/index.html.erb
<%= render '/home/jumbotron' unless user_signed_in? %>
<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box box-shadow">
      <div class="panel panel-default">
        <%= link_to (image_tag pin.image.url(:medium)), pin %><br/>
        <div class="panel-heading center">
          <em>"<%= pin.pun_text %>"</em>
        </div>
        <div class="panel-body panel-category">
          <h6>Category: <%= pin.category %></h6>
        </div>
        <div class="panel-footer">
          <h6>Added By: <strong><%= pin.user.name if pin.user %></strong></h6>
        </div>
      </div>
      <% if pin.user == current_user %>
        <div class="center">
          <%= link_to 'Edit', edit_pin_path(pin) %> |
          <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %><br/>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<div class="center">
  <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<div class="panel panel-default">
  <div class="panel panel-heading">
    <h1>New Pun</h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
  <div class="panel-footer">
    <%= link_to 'Back', pins_path %>
  </div>
</div>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-offset-5 col-md-4">
    <div class="box box-shadow">
      <div class="panel panel-default">
        <%= image_tag @pin.image.url(:medium) %><br/>
        <div class="panel-heading center">
          <em>"<%= @pin.pun_text %>"</em>
        </div>
        <div class="panel-body panel-category">
          <h6>Category: <%= @pin.category %></h6>
        </div>
        <div class="panel-footer">
          <h6><strong><%= @pin.user.name %></strong></h6>
        </div>
      </div>
      <div class="center">
        <% if @pin.user == current_user %>
          <%= link_to 'Edit', edit_pin_path(@pin) %> |
        <% end %>
        <%= link_to 'Back', pins_path %>
      </div>
    </div>
  </div>
</div>